Repository Neotys-Labs/neoload-cli, pull requests merged in 2021-03, with the labels that each got.

#137 Update changelog with auto-generated details; old one only went to 1.…
  CHANGELOG.md
  README.md
Labels: documentation

#133 Convert entity property values to string before filter compare
  neoload/neoload_cli_lib/filtering.py
  tests/neoload_cli_lib/test_filtering.py
Labels: bug

#141 fix(doc): Issues with gitlab openshit CI examples
  examples/pipelines/gitlab/openshift.gitlab-ci.yml
Labels: bug, documentation

#132 Fix trends back/ahead result selection logic
  neoload/commands/report.py
  tests/commands/report/test_trends_json_output.py
Labels: bug
